### ISSUE TITLE
Configuration to create an RDS instance?

### ISSUE THREAD

**Issue by jabr** [alienfast/elastic-beanstalk#10]
I'm haven't been able to figure out what options I need in my `config/eb.yml` to create an RDS instance. I've tried adding this block to options, but it doesn't seem to be enough:

``` yaml
  aws:rds:dbinstance:
    DBDeletionPolicy: Snapshot
    DBEngine: postgres
    DBInstanceClass: db.t1.micro
    DBUser: ebroot
```

Any ideas?
