### ISSUE TITLE
Speedier deployments - Approaches | Updates?

### ISSUE THREAD

**Issue by dashbitla** [alienfast/elastic-beanstalk#26]
Thank you and ThouhgtWorks team for the amazing Blue-Green deployment tool!

Any thoughts on how to do "Speedier deployments" that take care of bundle and Assets? Any ETA on the same?

There is a note in README:
"Speedier deployments - investigate caching of bundle and asset pre-compilation to see if there is a common setting to be found"

What approaches are possible / being evaluated?

**Comment by rosskevin** [comment]
What I have found is that assest precompilation on the continuous integration server is the best way to speed up deployment. I started to do this prior to my tests just to be sure I didn't have asset problems anyway,  and deploys were dramatically faster with no other changes necessary. 

I'm interested in hearing any other tips from others as well.

**Comment by rosskevin** [comment]
To skip asset precompile on server-side, we use:

```yaml
package:
  verbose: false
  includes:  ['public/assets/.sprockets-manifest-*.json']
  exclude_dirs: # defaults: pkg tmp log test-reports # additional dirs that merge with default excludes
    - doc
    - features
    - flows
    - spec
    - target
    - vcr
    - vendor
    - public/dev-assets
options:
  aws:elasticbeanstalk:application:environment:
    # we are doing asset compilation on CI
    RAILS_SKIP_ASSET_COMPILATION: true
```

Since we are using precompile in test, we set development to use `dev-assets` in `development.rb` with:

```ruby
  # don't get mixed up with test/production precompiled assets
  config.assets.prefix = '/dev-assets'
```
If you want to start a wiki page with what you find, I'm happy to add in stuff as I find it as well.

**Comment by dashbitla** [comment]
Thank you Kevin, exactly what I am looking for.
Once I get through the entire deployment process, I will do a Wiki!

I am writing few rake tasks that will be quite helpful, will send a PR shortly. 

Thank you for an amazing tool that you guys built.

**Comment by dashbitla** [comment]
One of our application uses themes and every customer gets their own theme and there are about 500+ themes. These themes assets and views files are all part of the application code itself and it uses themes_for_rails gem.

When the eb:package creates the package, the deployer package size is coming > 512MB inspite of excluding the folders that you had mentioned earlier. It fails to deploy with the error "Unable to create the application version source bundle is empty or exceeds maximum allowed size 524288000" as referenced in: https://forums.aws.amazon.com/thread.jspa?threadID=124356

I tried pushing all the STATIC assets from themes and assets folders to S3 and excluded the folders. It means - the application bundle doesn't have any static assets as part of the application. They are are precompiled and pushed to S3 using asset_sync gem. 

Application deployed fine, starts fine but not able to access the application as it fails with pre-compilation errors - as there is no such static asset file itself found on the application. 
```
ActionView::Template::Error (indicator.gif isn't precompiled):
    14:   <%= image_tag 'indicator.gif', :id => 'form-indicator', :style => 'display:none;' %> or 
```
I think these image_tag, styles & JS include tags expects the files to be there as part of the application to be able to expand the image with digest in the ERB generated views.

What is the best way to handle this situation? Appreciate your help.

**Comment by rosskevin** [comment]
I'm thinking that pushing to an S3 bucket is the right thing to do, I would stick cloudfront in front of the bucket so you have edge cdns working.

Do you have precompile set to off? 

```yaml
options:
  aws:elasticbeanstalk:application:environment:
    RAILS_SKIP_ASSET_COMPILATION: true
```
I assume so and you are failing in the rails layer, not the elastic beanstalk deployment correct?
