### ISSUE TITLE
Database Migrations - How does it work?

### ISSUE THREAD

**Issue by dashbitla** [alienfast/elastic-beanstalk#27]
Will the db:migrate runs on all the instances?
Is there a way to specify migrations to run only on one instance than on all the instances?

**Comment by rosskevin** [comment]
That's really a question to be answered by the aws documentation, but look for 'lead' instance,  I think that option is what you are looking for.

**Comment by rosskevin** [comment]
Found the related bit in the sample

```yaml
  03-rake.config:
    container_commands:
      01seed:
        command: rake db:seed
        leader_only: true
```
