### ISSUE TITLE
inactive_settings in eb.yml

### ISSUE THREAD

**Issue by killerham** [alienfast/elastic-beanstalk#32]
in eb_deployer you can do something like:

```
inactive_settings:
      # reduce instance count to 0 to save cost
      - namespace: aws:autoscaling:asg
        option_name: MinSize
        value: "0"
      # make sure cooldown is big enough to cope with DNS cache
      - namespace: aws:autoscaling:asg
        option_name: Cooldown
        value: "900"

```

what is the syntax for inactive settings for this gem?

**Comment by rosskevin** [comment]
Look at the readme sample and find aws:autoscaling:asg and you'll find other examples.  Our syntax is simpler and I believe our sample shows MinSize.

**Comment by killerham** [comment]
Yes but what about the inactive setting? I don't want to have two production servers running for my blue green setup as it is wasteful.

**Comment by rosskevin** [comment]
Do you not see the pattern based on MinSize? 

```yaml
options:

  aws:autoscaling:asg:
    MinSize: 1
```

This gem generates the option settings from the eb.yml.  If you are concerned it isn't going to be right,  create your package without deploying and inspect the aws option settings.

**Comment by killerham** [comment]
So for inactive settings it would be

```
inactive:
    aws:autoscaling:asg:
      MinSize: 0
      Cooldown: 900
```
right?

**Comment by rosskevin** [comment]
If that is a valid setting for aws elastic beanstalk, then yes that is how you would specify it.

**Comment by killerham** [comment]
I think its an eb_deployer specific setting as noted here:

https://github.com/ThoughtWorksStudios/eb_deployer/wiki/Elastic-Beanstalk-Tips-and-Tricks#set-inactive_settings-for-saving-cost-on-blue-green-deployment

**Comment by rosskevin** [comment]
@killerham there is an important distinction that I think you are misunderstanding - these are not `eb_deployer` settings, these are [AWS elastic beanstalk](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options.html#command-options-ruby) settings.

**Comment by killerham** [comment]
I know

```
aws:autoscaling:asg:
      MinSize: 0
      Cooldown: 900
```

are elastic beanstalk settings. I'm only worried about inactive_settings vs option_settings. I know that option_settings becomes option.... I'm wondering if inactive_settings becomes inactive.

**Comment by rosskevin** [comment]
I think I see what you are saying, here is the section that states that eb_deployer treats this in a special way: 

>  eb_deployer solves this problem by allow you set special settings to environments that only applied when they become inactive.

So they actually have a different settings root:

```yaml
option_settings:
      # providing least redundancy
      - namespace: aws:autoscaling:asg
        option_name: MinSize
        value: "2"
      # make sure cooldown is reset back to default when environment become active again
      - namespace: aws:autoscaling:asg
        option_name: Cooldown
        value: "360"
    inactive_settings:
      # reduce instance count to 0 to save cost
      - namespace: aws:autoscaling:asg
        option_name: MinSize
        value: "0"
      # make sure cooldown is big enough to cope with DNS cache
      - namespace: aws:autoscaling:asg
        option_name: Cooldown
        value: "900"
```

If you look at the generated .ebextensions from above, all of these will be under `options_settings`.  We need to add some code to recognize `options` vs `inactive` in our eb.yml.
