### ISSUE TITLE
Inactive settings cool down not being set

### ISSUE THREAD

**Issue by killerham** [alienfast/elastic-beanstalk#34]
When setting
```
inactive:
    aws:autoscaling:asg:
      MinSize: 0
      Cooldown: 900
```
It should wait 15 minutes before removing all instances. But its getting removed immediately. When doing show config, it does output the cool down setting, I just don't think it uses it.
