### ISSUE TITLE
Cannot apply inactive configuration

### ISSUE THREAD

**Issue by onomated** [alienfast/elastic-beanstalk#37]
Tried deploying with the inactive configuration as described but get an error from AWS tools on verification:

```
[environment:production-a-0000000] 'MyApp-production-inactive.elasticbeanstalk.com' now points to 'awseb-some-elb-id.us-east-1.elb.amazonaws.com'.
[environment:production-a-0000000] Completed swapping CNAMEs for environments 'production-b-1111111' and 'production-a-0000000'.
[environment:production-a-0000000] applying inactive settings...
[environment:production-a-0000000] Environment status: Ready
rake aborted!
Aws::ElasticBeanstalk::Errors::ConfigurationValidationException: Configuration validation exception: Invalid option value: '0' (Namespace: 'aws:autoscaling:updatepolicy:rollingupdate', OptionName: 'MaxBatchSize'): Value is less than minimum allowed value: 1
```

Used the inactive settings as prescribed in my `eb.yml`:
```
inactive:
  aws:autoscaling:asg:
    MinSize: 0
    Cooldown: 900
```

Is there a configuration missing?  Should the inactive block also take a `MaxSize` setting?

**Comment by rosskevin** [comment]
You need to check eb deployer's docs on this,  we merely pass through the settings.

**Comment by onomated** [comment]
Thanks.  I read eb deployer's docs which mimics this here.   I'll play around with this and see if we can really get this down to no instances in the ELB.

Thanks for this component btw! Life saver.

**Comment by rosskevin** [comment]
If you figure this out, please feel free to add a wiki page.

**Comment by onomated** [comment]
Ok, finally got to working on this.  Turns out my default config for all env deployments had rolling updates enabled.  In that case, it is invalid to set `MaxSize` and `MinSize` to zero.  I explicit disable rolling updates and this works.  
This should be updated in the main README since it is documented there.  Here's my inactive section that works for my deployment:

```
inactive:
  aws:autoscaling:asg:
    MinSize: 0
    MaxSize: 0
    Cooldown: 900
  aws:autoscaling:updatepolicy:rollingupdate:
    RollingUpdateEnabled: false
```
