### ISSUE TITLE
Using Latest Versions of Passenger - how to do?

### ISSUE THREAD

**Issue by dashbitla** [alienfast/elastic-beanstalk#39]
Right now Beanstalk comes with 4.x version of Passenger as an environment.
There are ton of advanced features with 5.x version of Passenger.
Is there any ways we can use latest version of Passenger with Nginx? Or Enterprise Passenger version??

**Comment by wpc** [comment]
@dashbitla 

I think you will need create a custom EB AMI. Documented [here] (http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.customenv.html).  Then set AMI id in eb_deployer.yml
```yaml
    - namespace: aws:autoscaling:launchconfiguration
      option_name: ImageId
      value: <your ami id>
```
Warning: I have never tried myself, but it seems straightforward.
