### ISSUE TITLE
Persistent environment variables

### ISSUE THREAD

**Issue by micahbf** [alienfast/elastic-beanstalk#52]
As it stands, deploying blows away any existing environment variables and replaces them with whatever's in the configuration.

However, there are some cases for which it would be nice to have persistent environment variables in EB - I'm thinking of things like Rails' `SECRET_KEY_BASE` which should not be stored in the repo, nor does it really make sense to have them in the local environment (since they are environment-specific).

Is there any way currently to have persistent environment variables in EB, or have others run into this issue?

**Comment by rosskevin** [comment]
I'm not using EB anymore, but this is right from the readme example `Any environment variables - will be available in ENV`:

``` yaml
options:

  # Any environment variables - will be available in ENV
  aws:elasticbeanstalk:application:environment:
    FOO: 'bar'
    RAILS_SKIP_ASSET_COMPILATION: true # Use if doing asset compilation before packaging (recommended)
```

Is this what you are using?
