### ISSUE TITLE
ebextensions not executing

### ISSUE THREAD

**Issue by KidA001** [alienfast/elastic-beanstalk#59]
In my `eb.yml` I have the following under `ebextensions`
```
ebextensions:
  files:
    "/opt/elasticbeanstalk/hooks/appdeploy/pre/001_oracle.sh":
      mode: "000755"
      owner: root
      group: root
      content: |
        #!/usr/bin/env bash
        ...
        ...
```

When I deploy my application, the script isn't executed and the file `/opt/elasticbeanstalk/hooks/appdeploy/pre/001_oracle.sh` is not in the directory. Am I doing something wrong?

**Comment by JeremiahChurch** [comment]
Hi @KidA001,

There's a bit of a trick to this - the ebextensions section of the yml file functionally creates files that would otherwise be in the ebextensions folder.

So you need to go one level deeper for files to end up on your server. Basically you need to specify an ebextension file that would create that file.

Rather than creating a new ebextensions file you could also package the files command with other commands in an ebextensions file - container_commands, packages, etc

An example:
```
ebextensions:
  files.config:
    files:
      "/opt/elasticbeanstalk/hooks/appdeploy/pre/001_oracle.sh":
        mode: "000755"
        content: |
            ...
````
