### ISSUE TITLE
How to specify/create a worker environment

### ISSUE THREAD

**Issue by KidA001** [alienfast/elastic-beanstalk#60]
I'd like to create a work environment. i can do this in the AWS console, but how do I specify that the environment is a worker environment in the `eb.yml` ?

```
develop-worker:
  options:
    aws:autoscaling:launchconfiguration:
      InstanceType: t2.small
  # what options specify worker?
```

**Comment by JeremiahChurch** [comment]
I believe the options value is `tier: Worker`

**Comment by KidA001** [comment]
@Tongboy are there AWS docs that correspond to the values I can add into eb.yml or are there restrictions on what I can enter?

For instance, the next question I have is I want to call this environment `develop-worker` but have it use the rails env `develop`

**Comment by JeremiahChurch** [comment]
Yeah - in general most of that can be found under http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/customize-containers.html

rails env is just an environment variable - easy to keep separated from the environment name

**Comment by KidA001** [comment]
@Tongboy thank you.

```
develop-worker:
  options:
    aws:autoscaling:launchconfiguration:
      InstanceType: t2.small
      Tier: Worker
```
or
```
develop-worker:
  options:
    Tier: Worker
    aws:autoscaling:launchconfiguration:
      InstanceType: t2.small
```
did not work. Trying to poke around for tier but not finding it

**Comment by KidA001** [comment]
@Tongboy thanks. Derp, I knew that was set by env variable 😬 

This seems to be working so far, thank you.
```
develop-worker:
  Tier: Worker
  options:
    aws:autoscaling:launchconfiguration:
      InstanceType: t2.small
```
