### ISSUE TITLE
Error when switching RAILS_ENV to production.

### ISSUE THREAD

**Issue by mhenry** [alienfast/elastic-beanstalk#8]
I've been deploying to AWS Elastic Beanstalk with this gem when RAILS_ENV is set to development, but recently I needed to deploy to production and I'm receiving the following error:

```
$ RAILS_ENV=production rake eb:package eb:deploy
rake aborted!
Don't know how to build task 'eb:package'
/Users/Mike/.rvm/gems/ruby-1.9.3-p448/bin/ruby_executable_hooks:15:in `eval'
/Users/Mike/.rvm/gems/ruby-1.9.3-p448/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```

My `config/eb.yml` file looks like this:

```
app: acme
region: us-east-1
solution_stack_name: 64bit Amazon Linux 2013.09 running Ruby 1.9.3

development:
  strategy: inplace_update
  options:
    aws:autoscaling:launchconfiguration:
      InstanceType: t1.micro
    aws:elasticbeanstalk:environment:
      EnvironmentType: SingleInstance

production:
  options:
    aws:autoscaling:launchconfiguration:
      InstanceType: t1.small

secrets_dir: config/aws
```

Any help would be appreciated. Thanks!
